#region AutoGenerated
using UnityEngine;

/// <summary>
/// Defines a channel for a message logged to the Console.
/// <para>
/// The contents of this class are auto-generated based on the channels added in Project Settings > Console.
/// </para>
/// <seealso cref="Debug.Log(int, string, Object)"/>
/// </summary>
public static class Channel
{
	public const int None = 0;
	public static readonly int tom = 1;
	public static readonly int tomre = 2;
	public static readonly int LocationRequest = 3;
	public static readonly int CanvasManager = 4;
	public static readonly int Setup = 5;
	public static readonly int GPSStartLocation = 6;
	public static readonly int StartEndLocations = 7;
	public static readonly int GoogleFitAPI = 8;
	public static readonly int HealthKitAPI = 9;
	public static readonly int MapQuestAPI = 10;
	public static readonly int HealthKitService = 11;
	public static readonly int GoogleFitService = 12;
	public static readonly int CalculateUserProgressIOS = 13;
	public static readonly int CalculateUserProgressAndroid = 14;
	public static readonly int MapImageIOS = 15;
	public static readonly int MapImageAndroid = 16;
	public static readonly int UIBlocksIOS = 17;
	public static readonly int UIBlocksAndroid = 18;
	public static readonly int ActivityGraphIOS = 19;
	public static readonly int ActivityGraphAndroid = 20;
	public static readonly int Charts = 21;
	public static readonly int UsefulFunctions = 22;
	public static readonly int BEHealthKit = 23;
	public static readonly int ChallengeInfo = 24;
	public static readonly int Statistics = 25;
}
#endregion